### ISSUE TITLE
This module will break on July 11th, 2018

### ISSUE THREAD

**Issue by geira** [jhthorsen/mojo-yr#3]
Just a quick heads up that this module will shortly stop working, due to hardcoded links to the wrong domain.

First of all, this module is a misnomer: You are using the MET Norway API (aka WeatherAPI), not the Yr API. Yr does indeed fetch their data from [api.met.no](https://api.met.no/i) (which is the canonical domain), but they also have [their own API](https://om.yr.no/info/verdata/) with a subset of our data, combined with a location database.

Now, for reasons lost in time Yr added api.yr.no as a CNAME to api.met.no some ten years ago, which has been redirected to api.met.no for several years now. However, Yr is now developing version 2.0 of their own API and have asked to have the domain back. As such we have notified our users via web, RSS and the mailing list that the domain api.yr.no will stop working on July 11th, 2018. You should all change your URLs to use api.met.no instead. 

In addition, several of the hardcoded product version numbers are no longer operational and must be updated, including locationforecast and sunrise. Also, since the TOS requires you to identify your app with a unique User-Agent header, the default value "Mojolicious (Perl)" is very likely to get you throttled. Finally, note that we now only supports HTTPS, and unencrypted calls will be redirected.

PS: After some quick testing it seems the current module does not handle redirects and so is already broken (actually must have been for years). I'm working on a patch and have made it work again, but I'm thinking this module should be deprecated in favor of a more generic and robust, Swagger-based client outside the YR namespace.

**Comment by jhthorsen** [comment]
I agree. I don't want to maintain this any longer.

What do you think @marcusramberg ?

**Comment by marcusramberg** [comment]
I'll release 0.07 with @geira 's PR, but I'll happily delist it once a better alternative hits metacpan.

**Comment by jhthorsen** [comment]
I'm going to close this issue. The module is no longer on CPAN.
